QT += core gui sql xml network printsupport script axcontainer
QT += core-private widgets-private gui-private

greaterThan(QT_MAJOR_VERSION, 5) {
    QT += core5compat
}

CONFIG += c++17

#TARGET digitalfarm

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    AdminPanel/DbManager.cpp \
    AdminPanel/adminwidget.cpp \
    Autorization/autorizationdialog.cpp \
    Debug/data.cpp \
    Debug/datetime.cpp \
    Debug/logger.cpp \
    FormsMenu/cell_check_and_edit.cpp \
    FormsMenu/damager.cpp \
    FormsMenu/dialog_form_dataentry_dataentry___milk_settings_add.cpp \
    FormsMenu/dialog_form_dataentry_settings___post_during.cpp \
    FormsMenu/form_1_1.cpp \
    FormsMenu/form_1_2.cpp \
    FormsMenu/form_1_2_general.cpp \
    FormsMenu/form_1_9_insemenation.cpp \
    FormsMenu/form_1_9_insemenation_s.cpp \
    FormsMenu/form_add_cow.cpp \
    FormsMenu/form_analyse_reports___reports.cpp \
    FormsMenu/form_analyse_reports___x_link.cpp \
    FormsMenu/form_dataentry_dataentry___batch_sampling.cpp \
    FormsMenu/form_dataentry_dataentry___dry_off.cpp \
    FormsMenu/form_dataentry_dataentry___dry_off__add.cpp \
    FormsMenu/form_dataentry_dataentry___fixed_feeding.cpp \
    FormsMenu/form_dataentry_dataentry___milk_separationoff.cpp \
    FormsMenu/form_dataentry_dataentry___milk_separationoff_add.cpp \
    FormsMenu/form_dataentry_dataentry___milk_settings.cpp \
    FormsMenu/form_dataentry_dataentry___transfer.cpp \
    FormsMenu/form_dataentry_dataentry___transfer_add_dialog.cpp \
    FormsMenu/form_dataentry_groups.cpp \
    FormsMenu/form_dataentry_robot.cpp \
    FormsMenu/form_dataentry_robot_dialog.cpp \
    FormsMenu/form_dataentry_routing_6_6_1.cpp \
    FormsMenu/form_dataentry_routing_6_6_1_add_dialog_.cpp \
    FormsMenu/form_dataentry_settings.cpp \
    FormsMenu/form_maintenance___backup_restoree.cpp \
    FormsMenu/form_maintenance___backup_restoree_dialog.cpp \
    FormsMenu/formlibrary_1_9.cpp \
    FormsMenu/formlibrary_1_9_tab_diseases_dialog.cpp \
    FormsMenu/formlibrary_1_9_tab_feed_types_dialog.cpp \
    FormsMenu/generatedbdata.cpp \
    FormsMenu/table_form_1_2_otel.cpp \
    FormsMenu/table_form_1_2_otel_add.cpp \
    FormsMenu/table_form_1_2_otel_add_calves_dialog.cpp \
    FormsMenu/table_form_2_1.cpp \
    FormsMenu/worker.cpp \
    Src/FilterLineEdit.cpp \
    Src/pbs/KoOdfNumberStyles.cpp \
    Src/pbs/pbsfileutil.cpp \
    Src/pbs/pbstools.cpp \
    Src/pbsDatabase/pbsdatabase.cpp \
    Src/pbsDatabase/pbsdbtools.cpp \
    Src/pbsDatabase/pbssqlitedatabase.cpp \
    Src/pbsappsettings.cpp \
    Src/pbscalculatethread.cpp \
    Src/pbsdatamodel.cpp \
    Src/pbsfilterframe.cpp \
    Src/pbsfooterframe.cpp \
    Src/pbsheaderview.cpp \
    Src/pbsmodelexporter.cpp \
    Src/pbstableprinter.cpp \
    Src/pbstableview.cpp \
    Src/pbstableviewitemdelegate.cpp \
    Src/pbstablewidget.cpp \
    Src/xlsx/source/xlsxabstractooxmlfile.cpp \
    Src/xlsx/source/xlsxabstractsheet.cpp \
    Src/xlsx/source/xlsxcell.cpp \
    Src/xlsx/source/xlsxcellformula.cpp \
    Src/xlsx/source/xlsxcelllocation.cpp \
    Src/xlsx/source/xlsxcellrange.cpp \
    Src/xlsx/source/xlsxcellreference.cpp \
    Src/xlsx/source/xlsxchart.cpp \
    Src/xlsx/source/xlsxchartsheet.cpp \
    Src/xlsx/source/xlsxcolor.cpp \
    Src/xlsx/source/xlsxconditionalformatting.cpp \
    Src/xlsx/source/xlsxcontenttypes.cpp \
    Src/xlsx/source/xlsxdatavalidation.cpp \
    Src/xlsx/source/xlsxdatetype.cpp \
    Src/xlsx/source/xlsxdocpropsapp.cpp \
    Src/xlsx/source/xlsxdocpropscore.cpp \
    Src/xlsx/source/xlsxdocument.cpp \
    Src/xlsx/source/xlsxdrawing.cpp \
    Src/xlsx/source/xlsxdrawinganchor.cpp \
    Src/xlsx/source/xlsxformat.cpp \
    Src/xlsx/source/xlsxmediafile.cpp \
    Src/xlsx/source/xlsxnumformatparser.cpp \
    Src/xlsx/source/xlsxrelationships.cpp \
    Src/xlsx/source/xlsxrichstring.cpp \
    Src/xlsx/source/xlsxsharedstrings.cpp \
    Src/xlsx/source/xlsxsimpleooxmlfile.cpp \
    Src/xlsx/source/xlsxstyles.cpp \
    Src/xlsx/source/xlsxtheme.cpp \
    Src/xlsx/source/xlsxutility.cpp \
    Src/xlsx/source/xlsxworkbook.cpp \
    Src/xlsx/source/xlsxworksheet.cpp \
    Src/xlsx/source/xlsxzipreader.cpp \
    Src/xlsx/source/xlsxzipwriter.cpp \
    adminpanel.cpp \
    basewindow.cpp \
    contextmenutable.cpp \
    csv/csvfile.cpp \
    dataanimals.cpp \
    db/GenerateDB.cpp \
    db/SqlDataBase.cpp \
    db/asyncsql/asyncmodelregister.cpp \
    db/asyncsql/asyncsqltablemodel.cpp \
    db/asyncsql/databaseconnection.cpp \
    db/asyncsql/databaseexception.cpp \
    db/asyncsql/queryrequest.cpp \
    db/asyncsql/queryresult.cpp \
    db/asyncsql/querythread.cpp \
    db/asyncsql/queryworker.cpp \
    db/database.cpp \
    form_2_1.cpp \
    form_dataentry_dataentry___batch_condition.cpp \
    form_in_work.cpp \
    form_list_cows.cpp \
    formlibrary_1_9_tab_series_dialog.cpp \
    formtemplate.cpp \
    hyphenator/hyphenationhash.cpp \
    hyphenator/hyphenator.cpp \
    hyphenator/hyphenatorfast.cpp \
    hyphenator/hyphenatortex.cpp \
    hyphenator/tex_patterns.cpp \
    hyphenator/texthyphenationformatter.cpp \
    json/json_w.cpp \
    main.cpp \
    main_digitalfarm.cpp \
    modelbuilder.cpp \
    qlineeditext.cpp \
    rwlock/ReadersWriterLock.cpp \
    rwlock/shd.cpp \
    rwlock/thr_safe.cpp \
    rwlock/tsmap.cpp \
    tabelwidget_module/checkboxitemdelegate.cpp \
    tabelwidget_module/comboboxitemdelegate.cpp \
    tabelwidget_module/datetimestyleditemdelegate.cpp \
    tabelwidget_module/spinboxitemdelegate.cpp \
    tabelwidget_module2/CustomDelegateView.cpp \
    tabelwidget_module2/CustomHeaderView.cpp \
    tabelwidget_module2/DataModel.cpp \
    tabelwidget_module2/TableModel.cpp \
    tabelwidget_module2/customdelegate.cpp \    
    table_form_1_2.cpp \
    table_form_1_2_batch_transfer.cpp \
    table_form_1_2_in_work.cpp \
    utils/Utils.cpp \
    utils/axistag.cpp \
    utils/customplot.cpp \
    utils/imageview.cpp \
    utils/qcustomplot.cpp \
    widget_form.cpp \
    widget_menu.cpp \
    utils/extendqtablewidget.cpp \
    utils/dialog_viewphoto.cpp \
    zf_itemview/private/zf_item_view_p.cpp \
    zf_itemview/private/zf_tree_view_p.cpp \
    zf_itemview/zf_error.cpp \
    zf_itemview/zf_header_view.cpp \
    zf_itemview/zf_html_tools.cpp \
    zf_itemview/zf_item_delegate.cpp \
    zf_itemview/zf_itemview_header_item.cpp \
    zf_itemview/zf_itemview_header_model.cpp \
    zf_itemview/zf_table_view.cpp \
    zf_itemview/zf_table_view_base.cpp \
    zf_itemview/zf_tree_view.cpp \
    zf_itemview/zf_utils.cpp

HEADERS += \
    AdminPanel/AdminWidget.h \
    AdminPanel/DbManager.h \
    AdminPanel/ui_DbManager.h \
    AdminPanel/ui_adminwidget.h \
    AdminPanel/ui_mainwidget.h \
    Autorization/autorizationdialog.h \
    Autorization/ui_autorizationdialog.h \
    Debug/data.h \
    Debug/datetime.h \
    Debug/logger.h \
    FormsMenu/cell_check_and_edit.h \
    FormsMenu/damager.h \
    FormsMenu/dialog_form_dataentry_dataentry___milk_settings_add.h \
    FormsMenu/dialog_form_dataentry_settings___post_during.h \
    FormsMenu/form_1_1.h \
    FormsMenu/form_1_2.h \
    FormsMenu/form_1_2_general.h \
    FormsMenu/form_1_9_insemenation.h \
    FormsMenu/form_1_9_insemenation_s.h \
    FormsMenu/form_add_cow.h \
    FormsMenu/form_analyse_reports___reports.h \
    FormsMenu/form_analyse_reports___x_link.h \
    FormsMenu/form_dataentry_dataentry___batch_sampling.h \
    FormsMenu/form_dataentry_dataentry___dry_off.h \
    FormsMenu/form_dataentry_dataentry___dry_off__add.h \
    FormsMenu/form_dataentry_dataentry___fixed_feeding.h \
    FormsMenu/form_dataentry_dataentry___milk_separationoff.h \
    FormsMenu/form_dataentry_dataentry___milk_separationoff_add.h \
    FormsMenu/form_dataentry_dataentry___milk_settings.h \
    FormsMenu/form_dataentry_dataentry___transfer.h \
    FormsMenu/form_dataentry_dataentry___transfer_add_dialog.h \
    FormsMenu/form_dataentry_groups.h \
    FormsMenu/form_dataentry_robot.h \
    FormsMenu/form_dataentry_robot_dialog.h \
    FormsMenu/form_dataentry_routing_6_6_1.h \
    FormsMenu/form_dataentry_routing_6_6_1_add_dialog_.h \
    FormsMenu/form_dataentry_settings.h \
    FormsMenu/form_maintenance___backup_restoree.h \
    FormsMenu/form_maintenance___backup_restoree_dialog.h \
    FormsMenu/formlibrary_1_9.h \
    FormsMenu/formlibrary_1_9_tab_diseases_dialog.h \
    FormsMenu/formlibrary_1_9_tab_feed_types_dialog.h \
    FormsMenu/generatedbdata.h \
    FormsMenu/table_form_1_2_otel.h \
    FormsMenu/table_form_1_2_otel_add.h \
    FormsMenu/table_form_1_2_otel_add_calves_dialog.h \
    FormsMenu/table_form_2_1.h \
    FormsMenu/ui_form_analyse_reports___reports.h \
    FormsMenu/ui_form_dataentry_routing_6_6_1_add_dialog_.h \
    FormsMenu/ui_form_dataentry_settings.h \
    FormsMenu/ui_table_form_2_1.h \
    FormsMenu/worker.h \
    Src/FilterLineEdit.h \
    Src/pbs/KoOdfNumberStyles.h \
    Src/pbs/pbsfileutil.h \
    Src/pbs/pbstools.h \
    Src/pbsDatabase/pbsdatabase.h \
    Src/pbsDatabase/pbsdbtools.h \
    Src/pbsDatabase/pbssqlitedatabase.h \
    Src/pbsappsettings.h \
    Src/pbscalculatethread.h \
    Src/pbsdatamodel.h \
    Src/pbsfilterframe.h \
    Src/pbsfooterframe.h \
    Src/pbsheaderview.h \
    Src/pbsmodelexporter.h \
    Src/pbstableprinter.h \
    Src/pbstableview.h \
    Src/pbstableviewitemdelegate.h \
    Src/pbstableviewtool.h \
    Src/pbstablewidget.h \
    Src/xlsx/header/xlsxabstractooxmlfile.h \
    Src/xlsx/header/xlsxabstractooxmlfile_p.h \
    Src/xlsx/header/xlsxabstractsheet.h \
    Src/xlsx/header/xlsxabstractsheet_p.h \
    Src/xlsx/header/xlsxcell.h \
    Src/xlsx/header/xlsxcell_p.h \
    Src/xlsx/header/xlsxcellformula.h \
    Src/xlsx/header/xlsxcellformula_p.h \
    Src/xlsx/header/xlsxcelllocation.h \
    Src/xlsx/header/xlsxcellrange.h \
    Src/xlsx/header/xlsxcellreference.h \
    Src/xlsx/header/xlsxchart.h \
    Src/xlsx/header/xlsxchart_p.h \
    Src/xlsx/header/xlsxchartsheet.h \
    Src/xlsx/header/xlsxchartsheet_p.h \
    Src/xlsx/header/xlsxcolor_p.h \
    Src/xlsx/header/xlsxconditionalformatting.h \
    Src/xlsx/header/xlsxconditionalformatting_p.h \
    Src/xlsx/header/xlsxcontenttypes_p.h \
    Src/xlsx/header/xlsxdatavalidation.h \
    Src/xlsx/header/xlsxdatavalidation_p.h \
    Src/xlsx/header/xlsxdatetype.h \
    Src/xlsx/header/xlsxdocpropsapp_p.h \
    Src/xlsx/header/xlsxdocpropscore_p.h \
    Src/xlsx/header/xlsxdocument.h \
    Src/xlsx/header/xlsxdocument_p.h \
    Src/xlsx/header/xlsxdrawing_p.h \
    Src/xlsx/header/xlsxdrawinganchor_p.h \
    Src/xlsx/header/xlsxformat.h \
    Src/xlsx/header/xlsxformat_p.h \
    Src/xlsx/header/xlsxglobal.h \
    Src/xlsx/header/xlsxmediafile_p.h \
    Src/xlsx/header/xlsxnumformatparser_p.h \
    Src/xlsx/header/xlsxrelationships_p.h \
    Src/xlsx/header/xlsxrichstring.h \
    Src/xlsx/header/xlsxrichstring_p.h \
    Src/xlsx/header/xlsxsharedstrings_p.h \
    Src/xlsx/header/xlsxsimpleooxmlfile_p.h \
    Src/xlsx/header/xlsxstyles_p.h \
    Src/xlsx/header/xlsxtheme_p.h \
    Src/xlsx/header/xlsxutility_p.h \
    Src/xlsx/header/xlsxworkbook.h \
    Src/xlsx/header/xlsxworkbook_p.h \
    Src/xlsx/header/xlsxworksheet.h \
    Src/xlsx/header/xlsxworksheet_p.h \
    Src/xlsx/header/xlsxzipreader_p.h \
    Src/xlsx/header/xlsxzipwriter_p.h \
    adminpanel.h \
    basewindow.h \
    contextmenutable.h \
    csv/csvfile.h \
    dataanimals.h \
    db/GenerateDB.h \
    db/SqlDataBase.h \
    db/asyncsql/asyncmodelregister.h \
    db/asyncsql/asyncsqltablemodel.h \
    db/asyncsql/databaseconnection.h \
    db/asyncsql/databaseexception.h \
    db/asyncsql/queryrequest.h \
    db/asyncsql/queryresult.h \
    db/asyncsql/querythread.h \
    db/asyncsql/queryworker.h \
    db/database.h \
    form_2_1.h \
    form_dataentry_dataentry___batch_condition.h \
    form_in_work.h \
    form_list_cows.h \
    formlibrary_1_9_tab_series_dialog.h \
    formtemplate.h \
    hyphenator/hyphenationhash.h \
    hyphenator/hyphenator.h \
    hyphenator/hyphenator_dll.h \
    hyphenator/hyphenatorfast.h \
    hyphenator/hyphenatortex.h \
    hyphenator/patterns.h \
    hyphenator/tex_patterns.h \
    hyphenator/texthyphenationformatter.h \
    json/json_w.h \
    main_digitalfarm.h \
    modelbuilder.h \
    qlineeditext.h \
    rwlock/ReadersWriterLock.h \
    rwlock/libh.h \
    rwlock/shd.h \
    rwlock/thr_safe.h \
    rwlock/tsmap.h \
    tabelwidget_module/checkboxitemdelegate.h \
    tabelwidget_module/comboboxitemdelegate.h \
    tabelwidget_module/datetimestyleditemdelegate.h \
    tabelwidget_module/spinboxitemdelegate.h \
    tabelwidget_module2/CustomDelegateView.h \
    tabelwidget_module2/CustomHeaderView.h \
    tabelwidget_module2/DataModel.h \
    tabelwidget_module2/TableModel.h \
    tabelwidget_module2/customdelegate.h \
    table_form_1_2.h \
    table_form_1_2_batch_transfer.h \
    table_form_1_2_in_work.h \
    ui_DbManager.h \
    ui_adminwidget.h \
    ui_autorizationdialog.h \
    ui_cell_check_and_edit.h \
    ui_dialog_form_dataentry_dataentry___milk_settings_add.h \
    ui_form_1_1.h \
    ui_form_1_2.h \
    ui_form_1_2_general.h \
    ui_form_1_9_add_cow.h \
    ui_form_1_9_insemenation.h \
    ui_form_1_9_insemenation_s.h \
    utils/Utils.h \
    utils/axistag.h \
    utils/customplot.h \
    utils/imageview.h \
    utils/qcustomplot.h \
    widget_form.h \
    widget_menu.h \
    utils/extendqtablewidget.h \
    utils/dialog_viewphoto.h \
    zf_itemview/private/zf_item_view_p.h \
    zf_itemview/private/zf_table_view_p.h \
    zf_itemview/private/zf_tree_view_p.h \
    zf_itemview/zf_error.h \
    zf_itemview/zf_header_view.h \
    zf_itemview/zf_html_tools.h \
    zf_itemview/zf_i_cell_column_check.h \
    zf_itemview/zf_item_delegate.h \
    zf_itemview/zf_itemview.h \
    zf_itemview/zf_itemview_header_item.h \
    zf_itemview/zf_itemview_header_model.h \
    zf_itemview/zf_table_view.h \
    zf_itemview/zf_table_view_base.h \
    zf_itemview/zf_tree_view.h \
    zf_itemview/zf_utils.h

FORMS += \
    AdminPanel/DbManager.ui \
    AdminPanel/adminwidget.ui \
    Autorization/autorizationdialog.ui \
    FormsMenu/cell_check_and_edit.ui \
    FormsMenu/dialog_form_dataentry_dataentry___milk_settings_add.ui \
    FormsMenu/dialog_form_dataentry_settings___post_during.ui \
    FormsMenu/form_1_1.ui \
    FormsMenu/form_1_2.ui \
    FormsMenu/form_1_2_general.ui \
    FormsMenu/form_1_9_insemenation.ui \
    FormsMenu/form_1_9_insemenation_s.ui \
    FormsMenu/form_add_cow.ui \
    FormsMenu/form_analyse_reports___reports.ui \
    FormsMenu/form_analyse_reports___x_link.ui \
    FormsMenu/form_dataentry_dataentry___batch_sampling.ui \
    FormsMenu/form_dataentry_dataentry___dry_off.ui \
    FormsMenu/form_dataentry_dataentry___dry_off__add.ui \
    FormsMenu/form_dataentry_dataentry___fixed_feeding.ui \
    FormsMenu/form_dataentry_dataentry___milk_separationoff.ui \
    FormsMenu/form_dataentry_dataentry___milk_separationoff_add.ui \
    FormsMenu/form_dataentry_dataentry___milk_settings.ui \
    FormsMenu/form_dataentry_dataentry___transfer.ui \
    FormsMenu/form_dataentry_dataentry___transfer_add_dialog.ui \
    FormsMenu/form_dataentry_groups.ui \
    FormsMenu/form_dataentry_robot.ui \
    FormsMenu/form_dataentry_robot_dialog.ui \
    FormsMenu/form_dataentry_routing_6_6_1.ui \
    FormsMenu/form_dataentry_routing_6_6_1_add_dialog_.ui \
    FormsMenu/form_dataentry_settings.ui \
    FormsMenu/form_maintenance___backup_restoree.ui \
    FormsMenu/form_maintenance___backup_restoree_dialog.ui \
    FormsMenu/formlibrary_1_9.ui \
    FormsMenu/formlibrary_1_9_tab_diseases_dialog.ui \
    FormsMenu/formlibrary_1_9_tab_feed_types_dialog.ui \
    FormsMenu/table_form_1_2_otel.ui \
    FormsMenu/table_form_1_2_otel_add.ui \
    FormsMenu/table_form_1_2_otel_add_calves_dialog.ui \
    FormsMenu/table_form_2_1.ui \
    adminpanel.ui \
    form_2_1.ui \
    form_dataentry_dataentry___batch_condition.ui \
    form_in_work.ui \
    form_list_cows.ui \
    formlibrary_1_9_tab_series_dialog.ui \
    main_digitalfarm.ui \
    table_form_1_2.ui \
    table_form_1_2_batch_transfer.ui \
    table_form_1_2_in_work.ui \
    widget_form.ui \
    widget_menu.ui \
    utils/dialog_viewphoto.ui

TRANSLATIONS += \
    prolely_ru_RU.ts
CONFIG += lrelease
CONFIG += embed_translations

#win32:RC_FILE = icons.rc

#win32:RC_FILE = icons.rc
#win32:OTHER_FILES += icons.rc
#win32: RC_ICONS = $$PWD/images/logo.ico
win32:RC_ICONS = digitalfarm.ico


# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    pbslib.qrc \
    resources/resources.qrc
